app/database/models.py
from sqlalchemy import Column, Integer, String, Unicode, DateTime, ForeignKey, Table
from sqlalchemy.orm import relationship
from app.database import Base
import datetime


# association_table = Table('association', Base.metadata,
#     Column('review_id', Integer, ForeignKey('reviews.review_id')),
#     Column('votes_id', Integer, ForeignKey('votes.review_id')),
#     Column('predictions_id', Integer, ForeignKey('predictions.review_id')),
#     Column('validated_data_id', Integer, ForeignKey('validated_data.review_id')),
#     Column('votes_id', Integer, ForeignKey('votes.review_id'))
#     )


class Review(Base):
    __tablename__ = 'reviews'
    review_id     = Column(Integer, primary_key = True)
    text          = Column(Unicode(None), unique = True)
    source        = Column(Unicode(50), unique = True)
    
    def __init__(self, text=None, source = 'Online Review'):
        self.text = text
        self.source = source
    
    def __repr__(self):
        return f'<Model:{self.review_id}> \n{self.text}'

class  Vote(Base):
    __tablename__ = 'votes'
    vote_id       = Column(Integer, primary_key = True)
    review_id     = Column(Integer, ForeignKey('reviews.review_id'), nullable=False)
    user_id       = Column(Integer, ForeignKey('users.user_id'), nullable=True)
    tag_id        = Column(Integer, ForeignKey('tags.tag_id'), nullable=True)
    vote          = Column(Unicode(20)) # options = [correct, not sure, incorrect]
    timestamp     = Column(DateTime, index=True, default=datetime.datetime.utcnow)
    



class Prediction(Base):
    __tablename__ = 'predictions'
    prediction_id = Column(Integer, primary_key = True)
    model_id      = Column(Integer, ForeignKey('models.model_id'), nullable=True)
    review_id     = Column(Integer, ForeignKey('reviews.review_id'), nullable=False)
    tag_id        = Column(Integer, ForeignKey('tags.tag_id'), nullable=True)
    timestamp     = Column(DateTime, index=True, default=datetime.datetime.utcnow)

class Tag(Base):
    __tablename__ = 'tags'
    tag_id        = Column(Integer, primary_key = True)
    label         = Column(Unicode(50), unique=True)
    value         = Column(Integer, unique=True)


    def __init__(self, label=None, value = None):
        self.label = label
    
    def __repr__(self):
        return f'<Tag:{self.tag_id}> {self.label}, {self.value}'

class Model(Base):
    __tablename__ = 'models'
    model_id       = Column(Integer, primary_key=True)
    model_name      = Column(Unicode(50), unique=True)
    
    def __init__(self, model_name=None):
        self.model_name = model_name
    
    def __repr__(self):
        return f'<Model:{self.model_id}> {self.model_name}'


class ValidatedData(Base):
    __tablename__= 'validated_data'
    validation_id   = Column(Integer, primary_key = True)
    review_id       = Column(Integer, ForeignKey('reviews.review_id'), nullable=False)
    validated_tags  = Column(Unicode(None), unique=True)
    validation_type = Column(Unicode(50), unique=True)

class User(Base):
    __tablename__ = 'users'
    user_id       = Column(Integer, primary_key=True)
    username      = Column(Unicode(50), unique=True)
    


    def __init__(self, username=None):
        self.username = username

    def __repr__(self):
        return f'<User:{self.user_id}> {self.username}'

app/__init__.py
from flask import Flask
from config import Config
from flask_migrate import Migrate

migrate = Migrate()

def create_app(config_class = Config):
    APP = Flask(__name__)
    APP.config.from_object(config_class)
    
    from app.database import Base
    migrate.init_app(APP, Base)

    from app.general import BP as general_bp
    APP.register_blueprint(general_bp, url_prefix ='/')

    from app.vader   import BP as vader_bp
    APP.register_blueprint(vader_bp, url_prefix='/vader')

    from app.reviews import BP as reviews_bp
    APP.register_blueprint(reviews_bp, url_prefix='/reviews')

    return APP

from app.database import models

app/database/__init__.py
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

import os

BASEDIR = os.path.abspath(os.path.dirname('__file__'))
DATABASE_URI = os.environ.get('DATABASE_URL') or 'sqlite:///' + os.path.join(BASEDIR, 'app.db')
engine = create_engine(DATABASE_URI, convert_unicode=True)    
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

Base = declarative_base()
Base.query = db_session.query_property()

def init_db():
    # import all modules here that might define models so that
    # they will be registered properly on the metadata.  Otherwise
    # you will have to import them first before calling init_db()
    import app.database.models
    Base.metadata.create_all(bind=engine)

app/general/__init__.py
from flask import Blueprint

BP = Blueprint('general', import_name=__name__)

from app.general import routes

app/general/routes.py
from flask import render_template, request, jsonify
from app.general import BP
from app.database import db_session
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

@BP.route('/')
def index():
    return render_template('general/template.html', selection='general')

app/reviews/__init__.py
from flask import Blueprint

BP = Blueprint('reviews', import_name=__name__)

from app.reviews import routes

app/reviews/routes.py
from flask import render_template, request, jsonify
from app.reviews import BP
from app.database import db_session
import pandas as pd
import os

# get reviews
filepath = os.path.join('app','reviews','data','2000reviews.pk')
assert os.path.isfile(filepath), f"2000 reviews not found in {filepath}"
data = pd.read_pickle(filepath) # columns = ['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText', 'overall', 'summary', 'unixReviewTime', 'reviewTime']


@BP.route('/')
def index():
    rnd_sentence = data[['reviewText', 'overall', 'summary']].sample()
    text    = rnd_sentence['reviewText'].values[0]
    rating  = rnd_sentence['overall'].values[0]
    summary = rnd_sentence['summary'].values[0]
    return render_template('reviews/index.html', 
                            selection='reviews', 
                            text = text, 
                            rating = rating, 
                            summary = summary)

app/vader/__init__.py
from flask import Blueprint

BP = Blueprint(
    name        = 'vader', 
    import_name = __name__,
    )

from app.vader import routes

app/vader/routes.py
from flask import render_template, current_app, request, jsonify
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from app.database import db_session
from app.vader import BP

@BP.route('/')
def index():
    return render_template('vader/index.html', selection='vader')


@BP.route('/predict', methods = ['POST', 'GET'])
def predict():
    
    if request.method == 'POST':
        
        text     = str(request.form.get('text'))
        analyzer = SentimentIntensityAnalyzer()
        vs       = analyzer.polarity_scores(text)
        
        return jsonify(vs)


    if request.method == 'GET':

        text     = str(request.args['text'])
        analyzer = SentimentIntensityAnalyzer()
        vs       = analyzer.polarity_scores(text)
        
        return jsonify(vs)

app/templates/general/template.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
  {% block styles %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
  {% block scripts_top %}{% endblock %}
</head>
<body class="my-body">
    <!-- ********************************************* -->
    <!-- NAVBAR -->
    <!-- ********************************************* -->
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto ml flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
            <h3 class="masthead-brand">SVA</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link {% if selection == 'general' %} active {% else %} inactive {% endif %}" href="{{url_for('general.index')}}">Home</a>
                <a class="nav-link {% if selection == 'vader'   %} active {% else %} inactive {% endif %}" href="{{url_for('vader.index')}}">Vader</a>
                <a class="nav-link {% if selection == 'reviews' %} active {% else %} inactive {% endif %}" href="{{url_for('reviews.index')}}">Reviews</a>
                <!-- <a class="nav-link" href="#">Contact</a> -->
            </nav>
            </div>
        </header>
    
    <!-- END NAVBAR -->
    <!-- ********************************************* -->
        
        {% block content %}{% endblock %}
    </div>
</body>

{% block scripts_bottom %}{% endblock %}
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
  <title>Vader Sentiment</title>
  <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
</head>
<body class="my-body">
  



<div class="cover-container d-flex w-100 h-100 p-3 mx-auto ml flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">VADER</h3>
      <nav class="nav nav-masthead justify-content-center">
      </nav>
    </div>
  </header>

  
  <main role="main" class="inner cover">
    <div class="mb-5">
      <h1   hidden id="compound">Majority</h1>
      <span hidden id="positive" class="badge badge-success">Success</span>
      <span hidden id="neutral" class="badge badge-secondary">Secondary</span>
      <span hidden id="negative" class="badge badge-danger">Danger</span>
    </div>
    <h4 class="cover-heading mb-3">type anything</h4>
    <form id="inputForm">
      <div class="form-group">
        <textarea class="form-control my-textarea" id="inputText"></textarea>
      </div>
      <button type="submit" class="btn mt-3  btn-primary">Predict Sentiment</button>
    </form>
  </main>



  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Demo of <a href="https://github.com/cjhutto/vaderSentiment">VADER-Sentiment-Analysis</a> by <a href="https://twitter.com/sebvargas_">@sebvargas_</a></p>
    </div>
  </footer>
</div>

</body>
</html>

app/templates/reviews/index.html
{% extends "general/template.html" %}
{% block title %}  Review Voting {% endblock %}
  <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
{% block styles %}{% endblock %}
{% block scripts_top %}
  <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
{% endblock %}



{% block content %}

<div class="card my-card">
    <div class="card-header my-card-header">
     Rating {{rating}}
    </div>
    <div class="card-body my-card-body">
      <h5 class="card-title">{{summary}}</h5>
      <p class="card-text">{{text}}</p>
    </div>
  </div>







<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><a href="https://twitter.com/sebvargas_">@sebvargas_</a></p>
  </div>
</footer>

{% endblock %}
</body>
</html>

app/templates/vader/index.html
{% extends "general/template.html" %}
  {% block title %}  Vader Sentiment {% endblock %}
    <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
  {% block styles %}{% endblock %}
  {% block scripts_top %}
    <script src="{{ url_for('static', filename = 'js/main.js') }}"></script>
  {% endblock %}



{% block content %}


  
  <main role="main" class="inner cover">
    <div class="mb-5">
      <h1   hidden id="compound">Majority</h1>
      <span hidden id="positive" class="badge badge-success">Success</span>
      <span hidden id="neutral" class="badge badge-secondary">Secondary</span>
      <span hidden id="negative" class="badge badge-danger">Danger</span>
    </div>
    <h4 class="cover-heading mb-3">type anything</h4>
    <form id="inputForm">
      <div class="form-group">
        <textarea class="form-control my-textarea" id="inputText"></textarea>
      </div>
      <button type="submit" class="btn mt-3  btn-primary">Predict Sentiment</button>
    </form>
  </main>



  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Demo of <a href="https://github.com/cjhutto/vaderSentiment">VADER-Sentiment-Analysis</a> by <a href="https://twitter.com/sebvargas_">@sebvargas_</a></p>
    </div>
  </footer>

{% endblock %}
</body>
</html>